-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local _mod = {}

local PERSON_TYPE_ENUM = protobuf.EnumDescriptor();
local PERSON_TYPE_ENUM_PTE_MAN_ENUM = protobuf.EnumValueDescriptor();
local PERSON_TYPE_ENUM_PTE_WOMEN_ENUM = protobuf.EnumValueDescriptor();
local PERSON = protobuf.Descriptor();
local PERSON_ID_FIELD = protobuf.FieldDescriptor();
local PERSON_NAME_FIELD = protobuf.FieldDescriptor();
local PERSON_EMAIL_FIELD = protobuf.FieldDescriptor();
local PHONE = protobuf.Descriptor();
local PHONE_PHONE_TYPE = protobuf.EnumDescriptor();
local PHONE_PHONE_TYPE_MOBILE_ENUM = protobuf.EnumValueDescriptor();
local PHONE_PHONE_TYPE_HOME_ENUM = protobuf.EnumValueDescriptor();
local PHONE_NUM_FIELD = protobuf.FieldDescriptor();
local PHONE_TYPE_FIELD = protobuf.FieldDescriptor();
local PHONE_PHONES_FIELD = protobuf.FieldDescriptor();
local PERSONGROUP = protobuf.Descriptor();
local PERSONGROUP_CLASSMATES_FIELD = protobuf.FieldDescriptor();

PERSON_TYPE_ENUM_PTE_MAN_ENUM.name = "PTE_MAN"
PERSON_TYPE_ENUM_PTE_MAN_ENUM.index = 0
PERSON_TYPE_ENUM_PTE_MAN_ENUM.number = 1
PERSON_TYPE_ENUM_PTE_WOMEN_ENUM.name = "PTE_WOMEN"
PERSON_TYPE_ENUM_PTE_WOMEN_ENUM.index = 1
PERSON_TYPE_ENUM_PTE_WOMEN_ENUM.number = 2
PERSON_TYPE_ENUM.name = "PERSON_TYPE_ENUM"
PERSON_TYPE_ENUM.full_name = ".PERSON_TYPE_ENUM"
PERSON_TYPE_ENUM.values = {PERSON_TYPE_ENUM_PTE_MAN_ENUM,PERSON_TYPE_ENUM_PTE_WOMEN_ENUM}
PERSON_ID_FIELD.name = "id"
PERSON_ID_FIELD.full_name = ".Person.id"
PERSON_ID_FIELD.number = 1
PERSON_ID_FIELD.index = 0
PERSON_ID_FIELD.label = 2
PERSON_ID_FIELD.has_default_value = false
PERSON_ID_FIELD.default_value = 0
PERSON_ID_FIELD.type = 4
PERSON_ID_FIELD.cpp_type = 4

PERSON_NAME_FIELD.name = "name"
PERSON_NAME_FIELD.full_name = ".Person.name"
PERSON_NAME_FIELD.number = 2
PERSON_NAME_FIELD.index = 1
PERSON_NAME_FIELD.label = 2
PERSON_NAME_FIELD.has_default_value = false
PERSON_NAME_FIELD.default_value = ""
PERSON_NAME_FIELD.type = 9
PERSON_NAME_FIELD.cpp_type = 9

PERSON_EMAIL_FIELD.name = "email"
PERSON_EMAIL_FIELD.full_name = ".Person.email"
PERSON_EMAIL_FIELD.number = 3
PERSON_EMAIL_FIELD.index = 2
PERSON_EMAIL_FIELD.label = 1
PERSON_EMAIL_FIELD.has_default_value = false
PERSON_EMAIL_FIELD.default_value = ""
PERSON_EMAIL_FIELD.type = 9
PERSON_EMAIL_FIELD.cpp_type = 9

PERSON.name = "Person"
PERSON.full_name = ".Person"
PERSON.nested_types = {}
PERSON.enum_types = {}
PERSON.fields = {PERSON_ID_FIELD, PERSON_NAME_FIELD, PERSON_EMAIL_FIELD}
PERSON.is_extendable = true
PERSON.extensions = {}
PHONE_PHONE_TYPE_MOBILE_ENUM.name = "MOBILE"
PHONE_PHONE_TYPE_MOBILE_ENUM.index = 0
PHONE_PHONE_TYPE_MOBILE_ENUM.number = 1
PHONE_PHONE_TYPE_HOME_ENUM.name = "HOME"
PHONE_PHONE_TYPE_HOME_ENUM.index = 1
PHONE_PHONE_TYPE_HOME_ENUM.number = 2
PHONE_PHONE_TYPE.name = "PHONE_TYPE"
PHONE_PHONE_TYPE.full_name = ".Phone.PHONE_TYPE"
PHONE_PHONE_TYPE.values = {PHONE_PHONE_TYPE_MOBILE_ENUM,PHONE_PHONE_TYPE_HOME_ENUM}
PHONE_NUM_FIELD.name = "num"
PHONE_NUM_FIELD.full_name = ".Phone.num"
PHONE_NUM_FIELD.number = 1
PHONE_NUM_FIELD.index = 0
PHONE_NUM_FIELD.label = 1
PHONE_NUM_FIELD.has_default_value = false
PHONE_NUM_FIELD.default_value = ""
PHONE_NUM_FIELD.type = 9
PHONE_NUM_FIELD.cpp_type = 9

PHONE_TYPE_FIELD.name = "type"
PHONE_TYPE_FIELD.full_name = ".Phone.type"
PHONE_TYPE_FIELD.number = 2
PHONE_TYPE_FIELD.index = 1
PHONE_TYPE_FIELD.label = 1
PHONE_TYPE_FIELD.has_default_value = false
PHONE_TYPE_FIELD.default_value = nil
PHONE_TYPE_FIELD.enum_type = PHONE_PHONE_TYPE
PHONE_TYPE_FIELD.type = 14
PHONE_TYPE_FIELD.cpp_type = 8

PHONE_PHONES_FIELD.name = "phones"
PHONE_PHONES_FIELD.full_name = ".Phone.phones"
PHONE_PHONES_FIELD.number = 10
PHONE_PHONES_FIELD.index = 0
PHONE_PHONES_FIELD.label = 3
PHONE_PHONES_FIELD.has_default_value = false
PHONE_PHONES_FIELD.default_value = {}
PHONE_PHONES_FIELD.message_type = PHONE
PHONE_PHONES_FIELD.type = 11
PHONE_PHONES_FIELD.cpp_type = 10

PHONE.name = "Phone"
PHONE.full_name = ".Phone"
PHONE.nested_types = {}
PHONE.enum_types = {PHONE_PHONE_TYPE}
PHONE.fields = {PHONE_NUM_FIELD, PHONE_TYPE_FIELD}
PHONE.is_extendable = false
PHONE.extensions = {PHONE_PHONES_FIELD}
PERSONGROUP_CLASSMATES_FIELD.name = "classmates"
PERSONGROUP_CLASSMATES_FIELD.full_name = ".PersonGroup.classmates"
PERSONGROUP_CLASSMATES_FIELD.number = 1
PERSONGROUP_CLASSMATES_FIELD.index = 0
PERSONGROUP_CLASSMATES_FIELD.label = 3
PERSONGROUP_CLASSMATES_FIELD.has_default_value = false
PERSONGROUP_CLASSMATES_FIELD.default_value = {}
PERSONGROUP_CLASSMATES_FIELD.message_type = PERSON
PERSONGROUP_CLASSMATES_FIELD.type = 11
PERSONGROUP_CLASSMATES_FIELD.cpp_type = 10

PERSONGROUP.name = "PersonGroup"
PERSONGROUP.full_name = ".PersonGroup"
PERSONGROUP.nested_types = {}
PERSONGROUP.enum_types = {}
PERSONGROUP.fields = {PERSONGROUP_CLASSMATES_FIELD}
PERSONGROUP.is_extendable = false
PERSONGROUP.extensions = {}

_mod.PTE_MAN = 1
_mod.PTE_WOMEN = 2
_mod.Person = protobuf.Message(PERSON)
_mod.PersonGroup = protobuf.Message(PERSONGROUP)
_mod.Phone = protobuf.Message(PHONE)
_mod.protobuf_Descriptor.PERSON_TYPE_ENUM = PERSON_TYPE_ENUM
_mod.protobuf_Descriptor.Person = PERSON 
_mod.protobuf_Descriptor.PersonGroup = PERSONGROUP 
_mod.protobuf_Descriptor.Phone = PHONE 

_mod.Person.RegisterExtension(PHONE_PHONES_FIELD)


return _mod
